### ISSUE TITLE
uploadin images and storage path 

### ISSUE THREAD

**Issue by hdk** [SlavaYurthev/Slider-M2#1]
magento security check recommends to set the web-root to the .../pub folder.

as a consequence, slider has to use .../pub/media/slider/<number>/bla.png as path on disk for images, but request them as /media/slider/<number>/bla.png via http.

the magic should happen via magento rewrites.

changing web-root to /pub, frontend loads slider pictures correctly, backend shows slider pictures correctly
BUT! when uploading pictures, slider put images to ../media/slider/<nr>/... on disk instead of ../pub/media/slider/<nr> (slider creates a new /media directory)

when magento web-root is set to magento root dir, everything is fine.

could you have a look at that?

**Comment by SlavaYurthev** [comment]
this is are not error, i hook this specially by many reasons
