### ISSUE TITLE
Problem when your host is on subfolder

### ISSUE THREAD

**Issue by tweetyx** [SlavaYurthev/Slider-M2#2]
Hi,
in app\code\SY\Slider\Controller\Adminhtml\Items\Save.php,
if you are in web url like
localhost/mywebsite/
the link of the image stay on localhost/

on other problem, when you save without file upload, magento get an error,
i add this condition
if($_FILES['image']['name'] != ''){

i put my code for resolve if it can help.

Question : do you work on this module for multi sliders ? We can just create one today.

Thanks

[Save.zip](https://github.com/SlavaYurthev/Slider-M2/files/1791007/Save.zip)

**Comment by SlavaYurthev** [comment]
Link issue will be fixed.
Uploading issue will be checked and fixed.
Multi-store functionality can be provided by custom ids filtering.

**Comment by SlavaYurthev** [comment]
subfolder and empty errors are fixed in 0.4.0
