### ISSUE TITLE
Database not working

### ISSUE THREAD

**Issue by tartreau** [SlavaYurthev/Slider-M2#8]
Hi, I've downloaded the .zip file, extracted it and ran setup:upgrade.

I can see the module through the backend, but when I go to the page to main page I have this error : 

> SQLSTATE[42S02]: Base table or view not found: 1146 Table 'magento.sy_slider' doesn't exist, query was: SELECT COUNT(*) FROM `sy_slider` AS `main_table`

I tried many thing to update the database, but nothing changed.

**Comment by SlavaYurthev** [comment]
You can create table by directly into mysql, just create table 'sy_slider' with columns these described in 
/Setup/InstallSchema.php
/Setup/UpgradeSchema.php
